//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorFinanciera.SPFileUploadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SPFileUploadService.ISPFileUpload")]
    public interface ISPFileUpload {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/TipoDeAutenticación", ReplyAction="http://tempuri.org/ISPFileUpload/TipoDeAutenticaciónResponse")]
        Infopoint.NET.Tipos.SPClientAuthenticationMode TipoDeAutenticación(string webURLSitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/AutenticaUsuario", ReplyAction="http://tempuri.org/ISPFileUpload/AutenticaUsuarioResponse")]
        bool AutenticaUsuario(Infopoint.NET.Credenciales credencial, string webURLSitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/ObtenColeccionDeItems", ReplyAction="http://tempuri.org/ISPFileUpload/ObtenColeccionDeItemsResponse")]
        Infopoint.NET.Tipos.SPItem[] ObtenColeccionDeItems(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/ObtenColeccionDeListas", ReplyAction="http://tempuri.org/ISPFileUpload/ObtenColeccionDeListasResponse")]
        Infopoint.NET.Tipos.SPList[] ObtenColeccionDeListas(Infopoint.NET.Credenciales credencial, string webURLSitio, Infopoint.NET.Tipos.SPFormaDatos queCampos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/ObtenColeccionDeTiposDeContenido", ReplyAction="http://tempuri.org/ISPFileUpload/ObtenColeccionDeTiposDeContenidoResponse")]
        Infopoint.NET.Tipos.SPContentType[] ObtenColeccionDeTiposDeContenido(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/AceptaDocumentos", ReplyAction="http://tempuri.org/ISPFileUpload/AceptaDocumentosResponse")]
        bool AceptaDocumentos(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/ObtenColeccionDeCarpetas", ReplyAction="http://tempuri.org/ISPFileUpload/ObtenColeccionDeCarpetasResponse")]
        Infopoint.NET.Tipos.SPFolder[] ObtenColeccionDeCarpetas(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/CargaArchivo", ReplyAction="http://tempuri.org/ISPFileUpload/CargaArchivoResponse")]
        bool CargaArchivo(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista, bool estitulolista, string carpeta, Microsoft.SharePoint.Client.FileCreationInformation archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/DescargaArchivo", ReplyAction="http://tempuri.org/ISPFileUpload/DescargaArchivoResponse")]
        System.IO.Stream DescargaArchivo(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/DescargaArchivoPorNombre", ReplyAction="http://tempuri.org/ISPFileUpload/DescargaArchivoPorNombreResponse")]
        System.IO.Stream DescargaArchivoPorNombre(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta, string nombreArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISPFileUpload/ObtenNombreFileStream", ReplyAction="http://tempuri.org/ISPFileUpload/ObtenNombreFileStreamResponse")]
        string ObtenNombreFileStream(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISPFileUploadChannel : ConectorFinanciera.SPFileUploadService.ISPFileUpload, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPFileUploadClient : System.ServiceModel.ClientBase<ConectorFinanciera.SPFileUploadService.ISPFileUpload>, ConectorFinanciera.SPFileUploadService.ISPFileUpload {
        
        public SPFileUploadClient() {
        }
        
        public SPFileUploadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPFileUploadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPFileUploadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPFileUploadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Infopoint.NET.Tipos.SPClientAuthenticationMode TipoDeAutenticación(string webURLSitio) {
            return base.Channel.TipoDeAutenticación(webURLSitio);
        }
        
        public bool AutenticaUsuario(Infopoint.NET.Credenciales credencial, string webURLSitio) {
            return base.Channel.AutenticaUsuario(credencial, webURLSitio);
        }
        
        public Infopoint.NET.Tipos.SPItem[] ObtenColeccionDeItems(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista) {
            return base.Channel.ObtenColeccionDeItems(credencial, webURLSitio, nombreLista, esTituloLista);
        }
        
        public Infopoint.NET.Tipos.SPList[] ObtenColeccionDeListas(Infopoint.NET.Credenciales credencial, string webURLSitio, Infopoint.NET.Tipos.SPFormaDatos queCampos) {
            return base.Channel.ObtenColeccionDeListas(credencial, webURLSitio, queCampos);
        }
        
        public Infopoint.NET.Tipos.SPContentType[] ObtenColeccionDeTiposDeContenido(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista) {
            return base.Channel.ObtenColeccionDeTiposDeContenido(credencial, webURLSitio, tituloLista);
        }
        
        public bool AceptaDocumentos(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista) {
            return base.Channel.AceptaDocumentos(credencial, webURLSitio, tituloLista);
        }
        
        public Infopoint.NET.Tipos.SPFolder[] ObtenColeccionDeCarpetas(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista) {
            return base.Channel.ObtenColeccionDeCarpetas(credencial, webURLSitio, nombreLista, esTituloLista);
        }
        
        public bool CargaArchivo(Infopoint.NET.Credenciales credencial, string webURLSitio, string tituloLista, bool estitulolista, string carpeta, Microsoft.SharePoint.Client.FileCreationInformation archivo) {
            return base.Channel.CargaArchivo(credencial, webURLSitio, tituloLista, estitulolista, carpeta, archivo);
        }
        
        public System.IO.Stream DescargaArchivo(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta) {
            return base.Channel.DescargaArchivo(credencial, webURLSitio, nombreLista, esTituloLista, carpeta);
        }
        
        public System.IO.Stream DescargaArchivoPorNombre(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta, string nombreArchivo) {
            return base.Channel.DescargaArchivoPorNombre(credencial, webURLSitio, nombreLista, esTituloLista, carpeta, nombreArchivo);
        }
        
        public string ObtenNombreFileStream(Infopoint.NET.Credenciales credencial, string webURLSitio, string nombreLista, bool esTituloLista, string carpeta) {
            return base.Channel.ObtenNombreFileStream(credencial, webURLSitio, nombreLista, esTituloLista, carpeta);
        }
    }
}
